
version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
  app:
    image: docker-spring-boot:latest
    build: .
    expose:
      - "8080"
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      TOKEN:
      CACHE_PORT: 6379
      CACHE_HOST: cache
    depends_on:
      - db
      - cache
  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
  nginx:
    image: nginx:latest
    volumes:
      - ./ngix.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl/:/ssl/:ro
    depends_on:
      - app
    ports:
      - "443:443"
      - "80:80"
